//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;
namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Event
    {
        public int EventId { get; set; }
        public string EventName { get; set; }
        public string EventDescription { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public System.Data.Entity.Spatial.DbGeography EventLocation { get; set; }
        public byte[] EventPicture { get; set;}
        public Nullable<int> EventPrice { get; set; }
    }
}
